import type { Config } from 'tailwindcss';

const config = {
  darkMode: ['class'],
  content: ['./src/**/*.{ts,tsx}', '../../packages/ui/src/**/*.{ts,tsx}'],
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      fontFamily: {
        sans: ['Inter', 'var(--font-sans)', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'label-md': ['Inter'],
        'body-md': ['Inter'],
        'headline-lg-mobile': ['Inter'],
        'label-sm': ['Inter'],
        'headline-md': ['Inter'],
        'headline-lg': ['Inter'],
        display: ['Inter'],
        'body-lg': ['Inter'],
        'body-sm': ['Inter'],
        'headline-sm': ['Inter'],
        button: ['Inter'],
      },
      fontSize: {
        'label-md': ['14px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '14px', letterSpacing: '0.02em', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg': [
          '32px',
          { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' },
        ],
        display: ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        button: ['16px', { lineHeight: '24px', fontWeight: '600' }],
      },
      spacing: {
        loose: '32px',
        'inset-equal': '16px',
        compact: '4px',
        comfortable: '16px',
        base: '8px',
        'inset-squish': '8px 16px',
        'stack-lg': '48px',
      },
      colors: {
        'tertiary-fixed-dim': '#b7c8e1',
        'on-primary-container': '#8192a7',
        'secondary-fixed-dim': '#80d5cb',
        'primary-fixed': '#d2e4fb',
        'on-error': '#ffffff',
        'primary-container': '#1a2b3c',
        surface: '#f7f9fb',
        'on-tertiary-container': '#8292aa',
        'on-primary-fixed': '#0b1d2d',
        'primary-fixed-dim': '#b7c8de',
        'outline-variant': '#c4c6cd',
        'surface-tint': '#4f6073',
        'on-secondary-fixed': '#00201d',
        'tertiary-container': '#1b2b3f',
        'surface-container': '#eceef0',
        'surface-variant': '#e0e3e5',
        'on-tertiary': '#ffffff',
        'on-secondary-container': '#006f67',
        'surface-container-lowest': '#ffffff',
        'on-primary-fixed-variant': '#38485a',
        'secondary-fixed': '#9cf2e8',
        'inverse-on-surface': '#eff1f3',
        'surface-dim': '#d8dadc',
        'on-surface': '#191c1e',
        'inverse-surface': '#2d3133',
        'on-error-container': '#93000a',
        tertiary: '#051629',
        'inverse-primary': '#b7c8de',
        'tertiary-fixed': '#d3e4fe',
        'on-primary': '#ffffff',
        'on-background': '#191c1e',
        outline: '#74777d',
        'on-surface-variant': '#44474c',
        'surface-container-highest': '#e0e3e5',
        'surface-container-high': '#e6e8ea',
        'on-secondary-fixed-variant': '#00504a',
        'on-secondary': '#ffffff',
        'surface-bright': '#f7f9fb',
        'error-container': '#ffdad6',
        'on-tertiary-fixed': '#0b1c30',
        'secondary-container': '#99efe5',
        'surface-container-low': '#f2f4f6',
        'on-tertiary-fixed-variant': '#38485d',

        // Keep Shadcn colors for compatibility with components
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: '#041627',
          foreground: '#ffffff',
        },
        secondary: {
          DEFAULT: '#006a63',
          foreground: '#ffffff',
        },
        destructive: {
          DEFAULT: '#ba1a1a',
          foreground: '#ffffff',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
      },
      borderRadius: {
        lg: '0.5rem',
        md: '0.25rem',
        sm: '0.125rem',
        xl: '0.75rem',
        '2xl': '1rem',
      },
    },
  },
  plugins: [],
} satisfies Config;

export default config;
